Creating SpacyTagger and SpacyChunker classes for using the transformer models in these two tasks
roshan-research/hazm pull request #307
Opened 2023-11-08 13:34 UTC by MortezaMahdaviMortazavi

I developed SpacyPOSTagger class and SpacyChunker class that we can use it for training transformer models with spacy api.Please check if there is anything wrong or redundancy

2023-11-09 11:10 UTC, imani requested changes
سلام. 
 لطفا موارد اعلام شده رو برطرف کنید. با توجه به این که سبک هر دو کلاس شبیه به هم هست بعضی از کامنت‌ها که در یک کلاس گذاشته شده در مورد کلاس دیگر هم صدق می‌کنه ولی کامنت گذاشته نشده که این موارد رو خودتون در نظر بگیرید.

سپاس

2023-11-09 11:10 UTC, imani commented on hazm/chunker.py
> +    def setup(self: "SpacyChunker", target_dataset_for_evaluation):
این تابع داخلی هست و بهتر هست با _ شروع شود

2023-11-09 11:10 UTC, imani commented on hazm/chunker.py
> +    def _parse(self: "SpacyChunker", sentence: List[Tuple[str, str, str]]) -> str:
این تابع اصلی هست و با _ نباید شروع شود

2023-11-09 11:10 UTC, imani commented on hazm/chunker.py
> +        doc = self.model(' '.join(w for w, _, tag in sentence))
پارامتر sentence در این تابع لیستی از tuple های دو تایی شامل word, pos_tag هست و سه تایی نیست.

2023-11-09 11:10 UTC, imani commented on hazm/chunker.py
> +        preds = [w.tag_ for w in doc]
حلقه‌های متعدد در این تابع باعث کندی عملکرد تابع میشه. لطفا تا جای ممکن از حلقه استفاده نکنید

2023-11-09 11:10 UTC, imani commented on hazm/chunker.py
> +            sent_preds = self._parse(sentence)
این تابع نباید از تابع parse استفاده کنه و بهتر هست که مستقیما خودش همه جمله‌ها رو یکجا به مدل بده و نتیجه رو یکجا بگیره تا سرعت بالاتری داشته باشه.

2023-11-09 11:10 UTC, imani commented on hazm/chunker.py
> +        return tuple(zip(words, tags, preds))
خروجی تابع باید به صورت درخت باشه و در نهایت برای return باید از تابع conlltags2tree استفاده کنید

2023-11-16 10:15 UTC, imani requested changes

2023-11-16 10:15 UTC, imani commented on hazm/pos_tagger.py
> +    def tag_sents(self:"SpacyPOSTagger",sents,batch_size):
لطفا تابع tag رو هم که فقط یک جمله میگیره اضافه کنید

2023-11-16 10:15 UTC, imani commented on hazm/pos_tagger.py
> +    def tag_sents(self:"SpacyPOSTagger",sents,batch_size):
یه پارامتر به tag و tag_sents اضافه کنید به اسم include_ez که به صورت پیش‌فرض true باشه و اگر true بود تگ‌های ez رو در خروجی بیاره و اگر false بود نیاره

2023-11-16 12:15 UTC, MortezaMahdaviMortazavi commented
Please check for new commits if they transmitted or not

2023-11-23 10:35 UTC, merged